---
abstract: 'A tool for managing CODEOWNERS files'
author:
  - 'Charles McGarvey <chazmcgarvey@brokenzipper.com>'
build_requires:
  Capture::Tiny: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::pushd: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Exit: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Codeowners
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  App::Codeowners:
    file: lib/App/Codeowners.pm
    version: '0.41'
  App::Codeowners::Options:
    file: lib/App/Codeowners/Options.pm
    version: '0.41'
  App::Codeowners::Util:
    file: lib/App/Codeowners/Util.pm
    version: '0.41'
  File::Codeowners:
    file: lib/File/Codeowners.pm
    version: '0.41'
  Test::File::Codeowners:
    file: lib/Test/File/Codeowners.pm
    version: '0.41'
recommends:
  Term::Detect::Software: '0'
  Unicode::GCString: '0'
requires:
  Carp: '0'
  Color::ANSI::Util: '0'
  Encode: '0'
  Exporter: '0'
  Getopt::Long: '2.39'
  IPC::Open2: '0'
  Path::Tiny: '0'
  Pod::Usage: '0'
  Scalar::Util: '0'
  Test::Builder: '0'
  Text::Gitignore: '0'
  Text::Table::Any: '0'
  perl: v5.10.1
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chazmcgarvey/git-codeowners/issues
  homepage: https://github.com/chazmcgarvey/git-codeowners
  repository: https://github.com/chazmcgarvey/git-codeowners.git
version: '0.41'
x_authority: cpan:CCM
x_generated_by_perl: v5.28.0
x_serialization_backend: 'YAML::Tiny version 1.73'
